name: Caching Primes

on: push

jobs:
  build:
    runs-on: ['self-hosted', 'org', 'terraform']

    steps:
    - name: Echo $HOME 1
      run: |
        echo "$HOME"

    - uses: actions/checkout@v4

    - name: Echo $HOME 2
      run: |
        echo "$HOME"

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v4
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        echo "123" > prime-numbers

    - name: Use Prime Numbers
      run: |
        if [ -f prime-numbers ]; then
          echo "Using cached prime numbers:"
          cat prime-numbers
        else
          echo "No cached prime numbers found."
        fi

