name: "[cLabs] Publish Docker Image For Release"

on:
  workflow_dispatch:
  release:
    types: [published]  # Trigger the workflow only when a release is published

jobs:
  Set-Tags:
    runs-on: ubuntu-latest
    steps:
      - name: Set tags
        id: set_tags
        run: |
          if [[ "${{ github.event.release.tag_name }}" == *"rc"* || "${{ github.event.release.tag_name }}" == *"beta"* || "${{ github.event.release.tag_name }}" == *"alpha"* ]]; then
            echo "tags=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "tags=${{ github.event.release.tag_name }},stable,latest" >> $GITHUB_ENV
          fi

  Build-Container-Test:
    permissions:
      contents: write
      actions: read
      pull-requests: write
      security-events: write
      attestations: write
      id-token: write
    concurrency:
      group:   ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    needs: Set-Tags
    uses: celo-org/reusable-workflows/.github/workflows/docker-build.yaml@v3.0.0-alvaro
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-tests-gh-workflows-actions/providers/github-by-repos
      service-account: tests-gh-workflows-actions@devopsre.iam.gserviceaccount.com
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/test-gh-workflows-actions
      tags: ${{ needs.set_tags.outputs.tags }}
      context: .
      trivy-enabled: true
