name: Caching Primes

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ['self-hosted', 'org', 'terraform']

    steps:
    - name: Harden Runner
      if: github.actor == 'github-hosted'
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - name: LS $HOME 1
      run: |
        ls -sail $HOME

    - name: LS $HOME 2
      run: |
        ls -sail /home/runner

    - uses: actions/checkout@v4

    - name: Echo $HOME 2
      run: |
        echo "$HOME"

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v4
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes

    - name: CAT
      run: |
        cat $HOME/prime-numbers

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        echo "123" > prime-numbers

    - name: Use Prime Numbers
      run: |
        if [ -f prime-numbers ]; then
          echo "Using cached prime numbers:"
          cat prime-numbers
        else
          echo "No cached prime numbers found."
        fi

