name: Test overwrite-image
run-name: "Overwrite the self hosted runners image"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  overwrite-image:
    name: Overwrite runner container image
    runs-on: ["self-hosted", "org", "8-cpu"]
    timeout-minutes: 2
    container:
      image: us-west1-docker.pkg.dev/devopsre/actions-runner-controller/celo-monorepo:34b1c5e90f9613964160cdf6bc292b410362ec6d
    steps:
      - name: Print OS info
        run: |
          cat /etc/os-release
          uname -a
